title: webpkr
description: webpkr - The webpack DSL

envs:
  development:
    url: "http://localhost:3000/"
    build: "http://localhost:8080/"
  production:
    url: "https://venkatperi.github.io/webpkr-doc/"
    build: "https://venkatperi.github.io/webpkr-doc/build/"

exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - package.json
  - .idea
  - package-lock.json
  - node_modules
  - src
  - webpkr
  - webpack.config.js
  - gulpfile.js
  - gulp.tasks.js
  - scss
  - .ignore
  - scripts

asciidoc: {}

asciidoctor:
  ext: asciidoc,adoc,ad
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=highlightjs
    - icons=font

google:
  analytics:
    id: "UA-62219190-2"
